### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by autuas** [xTooth/ToothTsoha#1]
*Projekti ladattu 1.10. n. klo 19.30*

### Heroku-sovellus

* Rekisteröityminen ja kirjautuminen toimivat ongelmitta
* Samalla käyttäjänimellä voi rekisteröityä vain kerran ja kaikki tekstikentät on täytettävä rekisteröitymisen yhteydessä, niin kuin on tarkoituskin
* Viestien katsominen myös kirjautumatta, viestien ja kommenttien luominen ja poistaminen onnistuvat hyvin
* Käyttötapauksissa mainittu käyttäjän profiilisivu jäi epäselväksi
* Sovelluksen ulkoasu on selkeä ja tyylikäs

### Koodi

Koodi on kauttaaltaan siistiä ja tarkoituksenmukaista. Koodia ei ole kommentoitu kovinkaan paljon, mutta sitä on nimeämiskäytännön loogisuuden vuoksi varsin helppo lukea. Kansio- ja tiedostorakenne on paljolti kurssin esimerkkisovelluksen kaltainen.

**Comment by xTooth** [comment]
Kiitos palautteesta!

> Käyttötapauksissa mainittu käyttäjän profiilisivu jäi epäselväksi
- Tätä en ole yksinkertaisesti toteuttanut vielä, lisään toiminnallisuuden lähipäivinä.
> Sovelluksen ulkoasu on selkeä ja tyylikäs
- Tämä on kieltämättä ollut hivenen huolenaihe koska optasin käyttämään pelkkiä kuvia, kuva+teksti yhdistelmien siasta. Kiva että on intuitiivinen tällä mallilla.
> Koodia ei ole kommentoitu kovinkaan paljon
- juu tämä täytyy ehdottomasti korjata.
