### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by ghost** [xTooth/ToothTsoha#3]
Projekti ladattu vertaisarvioitavaksi 15.10 klo 14:30

Käyttötapaukset:
- Kaikki käyttötapaukset näyttäisivät olevan toteutettuna ja toimivat kuten pitääkin. En onnistunut tuottamaan mitään näihin suoranaisesti liittyviä bugeja tai muita ihmeellisyyksiä testatessani ohjelmaa

Koodin laatu ja ymmärrettävyys:
- Koodi näyttää olevan enimmäkseen siistiä ja hyvin luettavaa
- Funktioiden ja muuttujien ym. nimentä on yhdenmukaista
- Koodissa toteutetut luokat ja niiden väliset riippuvuudet vastaavat tietokantakaaviota

Pikkuvirheet ja muut huomiot:
- Käyttöoheissa kehotetaan ajamaan juuresta app.py, pitäisi olla run.py
- Postaukset ja kommentit validoidaan tyhjän syötteen varalta, mutta hyväksyy kuitenkin jos niihin syöttää pelkkää whitespacea
- Postausaika näytetään UTC-ajassa, ei käyttäjän ajassa (postaan klo 16 suomen ajassa, näyttää että olisin postannut klo 13)
- post_edit-, comment_edit- ja comment_delete -routeilta puuttuu @login_required -dekoraattori, mahdollistaa muokkaamisen tai poistamisen ilman kirjautumista esim Postmanilla jos id on tiedossa.
- post_edit-, post_delete-, comment_edit- ja comment_delete -routeissa ei tarkisteta sitä kuka kirjautunut käyttäjä on, eli nämä voi teoriassa tehdä toisena käyttäjänä Postmania tai muuta REST-clienttiä käyttäen.

Hyvältä näyttää kokonaisuudessaan, noita pikkujuttuja lukuunottamatta.

**Comment by xTooth** [comment]
Kiitos palautteesta!
Toit hyvin esiin muutaman seikan mikä on jäänyt huomioimatta, etenkin nuo validoinnit liittyen kirjautumiseen ja syötteisiin! Siirrynkin tästä korjailemaan noita!
